version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
      
jobs:
  launch-bot:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          node index.js

workflows:
  my-custom-workflow:
    jobs:
      - launch-bot